#!/usr/bin/env python3

from sys import argv
from pseudomyth import automatic_mode, legacy_mode


if __name__ == '__main__':
    if not argv[-1] == 'legacy':
        automatic_mode()
    else:
        legacy_mode()
